# Generated by Django 5.2.4 on 2025-08-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=10)),
                ('dew_point', models.CharField(max_length=10)),
                ('humidity', models.CharField(max_length=10)),
                ('wind_speed', models.CharField(max_length=10)),
                ('visibility', models.CharField(max_length=10)),
                ('pressure', models.CharField(max_length=10)),
                ('res', models.CharField(max_length=100)),
            ],
        ),
    ]
